all:
	make -C lesson01
	make -C lesson02
	make -C lesson03
	make -C lesson04
	make -C lesson05
	make -C lesson06
	make -C lesson07
	make -C lesson08
	make -C lesson09
	make -C lesson10
	make -C lesson11
	make -C lesson12
	make -C lesson13
	make -C lesson14
	make -C lesson15
	make -C lesson16
	make -C lesson17
	make -C lesson18
	make -C lesson19
	make -C lesson20
	make -C lesson21
	make -C lesson22
	make -C lesson23
	make -C lesson24
	make -C lesson25
	make -C lesson26
	make -C lesson27
	make -C lesson28
	make -C lesson29
	make -C lesson30
	make -C lesson31
	make -C lesson32
	make -C lesson33
	make -C lesson34
	make -C lesson35
	make -C lesson36

clean:
	make -C lesson01 clean
	make -C lesson02 clean
	make -C lesson03 clean
	make -C lesson04 clean
	make -C lesson05 clean
	make -C lesson06 clean
	make -C lesson07 clean
	make -C lesson08 clean
	make -C lesson09 clean
	make -C lesson10 clean
	make -C lesson11 clean
	make -C lesson12 clean
	make -C lesson13 clean
	make -C lesson14 clean
	make -C lesson15 clean
	make -C lesson16 clean
	make -C lesson17 clean
	make -C lesson18 clean
	make -C lesson19 clean
	make -C lesson20 clean
	make -C lesson21 clean
	make -C lesson22 clean
	make -C lesson23 clean
	make -C lesson24 clean
	make -C lesson25 clean
	make -C lesson26 clean
	make -C lesson27 clean
	make -C lesson28 clean
	make -C lesson29 clean
	make -C lesson30 clean
	make -C lesson31 clean
	make -C lesson32 clean
	make -C lesson33 clean
	make -C lesson34 clean
	make -C lesson35 clean
	make -C lesson36 clean
